"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Compass, Mail, MapPin, Phone } from "lucide-react";
import Link from "next/link";
import VisitorStats from "./VisitorStats";
import { CONTACT_INFO } from "@/lib/constant";
export default function Footer() {
    return (_jsx("footer", { className: "bg-slate-950 text-white font-sans pt-20 pb-8 border-t border-slate-900", children: _jsxs("div", { className: "max-w-7xl mx-auto px-6 md:px-8", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12 mb-16", children: [_jsxs("div", { className: "flex flex-col gap-6", children: [_jsxs(Link, { href: "/", className: "flex items-center gap-3 group w-fit", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-white/10 text-white flex items-center justify-center", children: _jsx(Compass, { className: "w-6 h-6" }) }), _jsxs("div", { children: [_jsx("div", { className: "font-bold text-lg leading-tight text-white", children: "CV. An Nasr Konsultan" }), _jsx("div", { className: "text-xs font-medium tracking-wide text-slate-400", children: "Konsultan Teknik & Konstruksi" })] })] }), _jsx("p", { className: "text-slate-400 text-sm leading-relaxed max-w-sm", children: "Penyedia jasa konsultansi teknik sipil, perencanaan, pengawasan, perizinan, dan konstruksi di Kabupaten Jombang, Jawa Timur." })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-base tracking-wide mb-6 uppercase text-slate-200", children: "Menu" }), _jsx("ul", { className: "flex flex-col gap-3", children: [
                                        { name: "Beranda", href: "/" },
                                        { name: "Tentang Kami", href: "/tentang" },
                                        { name: "Layanan", href: "/layanan" },
                                        { name: "Portfolio", href: "/portfolio" },
                                        { name: "Klien Kami", href: "/klien" },
                                        { name: "Karir", href: "/karir" },
                                        { name: "Kontak", href: "/kontak" },
                                    ].map((item) => (_jsx("li", { children: _jsx(Link, { href: item.href, className: "text-slate-400 text-sm hover:text-lime-400 transition-colors font-medium", children: item.name }) }, item.name))) })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-base tracking-wide mb-6 uppercase text-slate-200", children: "Layanan" }), _jsx("ul", { className: "flex flex-col gap-3", children: [
                                        { name: "Jasa Perencanaan", href: "/layanan/perencanaan" },
                                        { name: "Jasa Pengawasan", href: "/layanan/pengawasan" },
                                        { name: "Jasa Perizinan", href: "/layanan/perizinan" },
                                        { name: "Jasa Konstruksi", href: "/layanan/konstruksi" },
                                    ].map((item) => (_jsx("li", { children: _jsx(Link, { href: item.href, className: "text-slate-400 text-sm hover:text-lime-400 transition-colors font-medium", children: item.name }) }, item.name))) })] }), _jsxs("div", { className: "flex flex-col gap-6", children: [_jsx("h3", { className: "font-bold text-base tracking-wide mb-2 uppercase text-slate-200", children: "Kontak" }), _jsxs("ul", { className: "flex flex-col gap-4", children: [_jsxs("li", { className: "flex gap-3 items-start", children: [_jsx(MapPin, { className: "w-5 h-5 text-lime-400 shrink-0 mt-0.5" }), _jsx("span", { className: "text-slate-400 text-sm leading-relaxed", children: CONTACT_INFO.address })] }), _jsxs("li", { className: "flex gap-3 items-center", children: [_jsx(Phone, { className: "w-5 h-5 text-lime-400 shrink-0" }), _jsx(Link, { href: `tel:${CONTACT_INFO.phoneNumberClean}`, className: "text-slate-400 text-sm hover:text-lime-400 transition-colors font-medium", children: CONTACT_INFO.phone })] }), _jsxs("li", { className: "flex gap-3 items-center", children: [_jsx(Mail, { className: "w-5 h-5 text-lime-400 shrink-0" }), _jsx(Link, { href: `mailto:${CONTACT_INFO.email}`, className: "text-slate-400 text-sm hover:text-lime-400 transition-colors font-medium", children: CONTACT_INFO.email })] })] })] })] }), _jsx("div", { className: "mb-16", children: _jsx(VisitorStats, {}) }), _jsxs("div", { className: "border-t border-slate-900 pt-8 flex flex-col md:flex-row items-center justify-between gap-4", children: [_jsx("p", { className: "text-slate-500 text-xs text-center md:text-left", children: "\u00A9 2026 CV. AN NASR KONSULTAN. Seluruh hak cipta dilindungi." }), _jsxs("div", { className: "flex gap-6", children: [_jsx(Link, { href: "/privacy", className: "text-slate-500 hover:text-slate-400 text-xs transition-colors", children: "Kebijakan Privasi" }), _jsx(Link, { href: "/terms", className: "text-slate-500 hover:text-slate-400 text-xs transition-colors", children: "Syarat & Ketentuan" })] })] })] }) }));
}
