import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import PortfolioGrid from "@/components/PortfolioGrid";
import Link from "next/link";
import { PORTFOLIO_PROJECTS, PORTFOLIO_CATEGORIES } from "@/lib/constant";
const PROJECTS = PORTFOLIO_PROJECTS;
const CATEGORIES = PORTFOLIO_CATEGORIES;
export default function PortfolioPage() {
    return (_jsxs("div", { className: "bg-white min-h-screen font-sans", children: [_jsxs("section", { className: "bg-slate-900 text-white py-20 relative overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-blue-950 to-slate-950 z-0 opacity-90" }), _jsx("div", { className: "absolute inset-0 bg-[linear-gradient(to_right,#ffffff03_1px,transparent_1px),linear-gradient(to_bottom,#ffffff03_1px,transparent_1px)] bg-[size:3rem_3rem]" }), _jsxs("div", { className: "relative z-10 max-w-7xl mx-auto px-6 md:px-8", children: [_jsx("span", { className: "text-lime-400 font-bold tracking-widest text-xs uppercase mb-3 inline-block", children: "Dokumentasi Kerja" }), _jsx("h1", { className: "text-4xl md:text-5xl font-black tracking-tight mb-4", children: "Portfolio Proyek Kami" }), _jsx("p", { className: "text-slate-300 text-base md:text-lg max-w-2xl leading-relaxed", children: "Kumpulan proyek perencanaan, pengawasan, perizinan, dan pelaksanaan konstruksi yang diselesaikan dengan standar teknis terbaik." })] })] }), _jsx("section", { className: "py-16 md:py-24", children: _jsx("div", { className: "max-w-7xl mx-auto px-6 md:px-8", children: _jsx(PortfolioGrid, { projects: PROJECTS, categories: CATEGORIES }) }) }), _jsx("section", { className: "py-16 bg-blue-900 text-white text-center", children: _jsxs("div", { className: "max-w-4xl mx-auto px-6", children: [_jsx("h3", { className: "text-2xl md:text-3xl font-extrabold mb-6", children: "Miliki Standar Kualitas yang Sama untuk Proyek Anda" }), _jsx("p", { className: "text-blue-100 text-sm max-w-xl mx-auto mb-8", children: "Hubungi tim CV. AN NASR KONSULTAN untuk menyusun rancangan anggaran dan perencanaan teknis proyek pembangunan Anda." }), _jsx(Link, { href: "/kontak", className: "px-8 py-3.5 rounded-full text-sm font-bold bg-lime-500 text-slate-950 hover:bg-lime-400 hover:scale-105 transition-all inline-flex items-center shadow-md", children: "Hubungi Kami Sekarang" })] }) })] }));
}
